# Generated by Django 2.0.6 on 2018-06-26 10:27

import carousel.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carousel', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='location',
            field=models.ImageField(blank=True, null=True, upload_to=carousel.models.get_image_path),
        ),
    ]
