# Generated by Django 2.0.6 on 2018-06-26 10:40

import carousel.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carousel', '0003_auto_20180626_1036'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='location',
            field=models.ImageField(upload_to=carousel.models.get_image_path),
        ),
    ]
